# Generated by Django 5.0 on 2024-02-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0002_friendship_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
