# Generated by Django 5.0 on 2024-02-27 18:54

import protoAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0005_profile_profile_photo_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.ImageField(blank=True, null=True, upload_to=protoAuth.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=protoAuth.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=protoAuth.models.user_directory_path),
        ),
    ]
