# Generated by Django 5.0 on 2024-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0006_alter_profile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
