# Generated by Django 5.0 on 2024-03-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0008_profile_name_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
