# Generated by Django 5.0 on 2024-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0012_profile_name_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
