# Generated by Django 5.0 on 2024-03-02 01:29

import protoAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0016_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to=protoAuth.models.user_directory_path),
        ),
    ]
