# Generated by Django 5.0 on 2024-03-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0017_alter_profile_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passage_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
